### ISSUE TITLE
Laravel dependency remove

### ISSUE THREAD

**Issue by andrii-pukhalevych** [nakanakaii/countries#4]
Is it required to have laravel dependency? 
Tried to use list in non-laravel project, but its not possible.

**Comment by nakanakaii** [comment]
Hi @andrii-pukhalevych,

after reconsideration of dependency `laravel/framework` I used to make this package's service provider, I can remove it and depend on [illuminate/support](https://packagist.org/packages/illuminate/support) instead. This would keep the intended behavior in laravel projects and also make the package useful in non-laravel projects.

Please wait for further updates on this thread.

**Comment by nakanakaii** [comment]
changes were made in https://github.com/nakanakaii/countries/pull/5 and now available on [v1.0.3](https://github.com/nakanakaii/countries/releases/tag/v1.0.3)

**Comment by andrii-pukhalevych** [comment]
I had to add in my composer json:
```
  "replace": {
    "illuminate/support": "*"
  },

```
Otherwice in my non-laravel project it installs following unused packages:

  - Installing voku/portable-ascii (2.0.1): Downloading (100%)         
  - Installing symfony/polyfill-php80 (v1.31.0): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.31.0): Loading from cache
  - Installing psr/container (2.0.2): Downloading (100%)         
  - Installing psr/simple-cache (3.0.0): Downloading (100%)         
  - Installing symfony/translation-contracts (v3.5.0): Downloading (100%)         
  - Installing symfony/translation (v6.4.13): Downloading (100%)         
  - Installing psr/clock (1.0.0): Loading from cache
  - Installing carbonphp/carbon-doctrine-types (3.2.0): Downloading (100%)         
  - Installing nesbot/carbon (2.72.5): Downloading (100%)         
  - Installing doctrine/inflector (2.0.10): Downloading (100%)         
  - Installing illuminate/macroable (v10.48.24): Downloading (100%)         
  - Installing illuminate/contracts (v10.48.24): Downloading (100%)         
  - Installing illuminate/conditionable (v10.48.24): Downloading (100%)         
  - Installing illuminate/collections (v10.48.24): Downloading (100%)         
  - Installing illuminate/support (v10.48.24): Downloading (100%) 

Looks too much just for list of countries ;)
